### ISSUE TITLE
Result of new m.Main() is an Empty object

### ISSUE THREAD

**Issue by QuantumInformation** [ModuleLoader/es6-module-loader#375] opened 2015-05-12 18:40 UTC
Presently I am wanting to write code that is used in the browser with the es6-module-loader and babel. The code is transpiled in the browser with babel.

I run my tests with qunit in this callback:

    var classToTest;//this will be tested by qunit later
    System.transpiler = 'babel';
    System.import('app/main').then(function (m) {
      classToTest = new m.Main(); //this will be tested by qunit later
      runTests();
    });
    
However when this runs classToTest is just an empty object when inspected in the debugger () so my tests fail:

classToTest value at line : runTests();
 

       Main {}

The strange thing is Main performs all the things it is meant to do:

import ShoppingCart from './shoppingCart'

    export class Main {
      constructor() {
        //todo look at a way to run this code after all dom is loaded
        //document.addEventListener("DOMContentLoaded", function (event) {
        //});
    
        //check if cart has stored items otherwise init with default items
        let cart;
        let items = localStorage.getItem("items");
        console.log(items);
        let parsedItems = JSON.parse(localStorage.getItem("items"));
    
        if (parsedItems === null) {
          cart = new ShoppingCart(['Ferrari F40', 'S Class', 'Tesla'], document.querySelector('#app'))
          //
        } else if (parsedItems === "") { //its been saved before but is empty (user deleted all items)
          cart = new ShoppingCart([], document.querySelector('#app'))
          //
        } else { // has user saved items
          cart = new ShoppingCart(parsedItems, document.querySelector('#app'))
        }
      }
    }

**Comment by MajorBreakfast** [comment] 2015-05-13 11:47
I don't see any rarely used API here, and no reason for why that wouldn't work. I think that the problem is in the integration with qunit. You should try to replicate the bug in a small test project.

BTW use ```JS to start a JavaScript code block in a github issue.

**Comment by QuantumInformation** [comment] 2015-05-14 07:44
hi @MajorBreakfast would you be able to try this project out?

https://github.com/QuantumInformation/vanilla-es6-shoppingcart/commits?author=QuantumInformation

If you run the test.html and look at this line you will see that classToTest is {}

```js
    var classToTest;//this will be tested by qunit later
    System.transpiler = 'babel';
    System.import('app/main').then(function (m) {
      classToTest = new m.Main(); //this will be tested by qunit later
      runTests();
    });
```

**Comment by crsmithdev** [comment] 2015-05-19 02:39
I am seeing the same issue.

**Comment by guybedford** [comment] 2015-05-20 10:04
@crsmithdev can you clarify what you mean that you're seeing the same issue?

**Comment by guybedford** [comment] 2015-05-20 10:05
@QuantumInformation it could be worth ensuring you're running the latest version of Babel as well here.

**Comment by guybedford** [comment] 2015-05-20 10:09
@QuantumInformation the class in https://github.com/QuantumInformation/vanilla-es6-shoppingcart/blob/master/app/main.js#L3 has no prototype methods - so you will be getting an empty object for the class. Closing as this is a class implementation issue - just let me know if you have any further questions.

**Closed by guybedford** 2015-05-20 10:09 UTC
Labels: support
